### ISSUE TITLE
When I created the file and wrote the file template, an error occurred

### ISSUE THREAD

**Issue by xinmodao** [doganalper/template.nvim#11] opened 2024-06-13 02:08 UTC
Thank you for your work. This plugin is what I need, but I encountered the following error while using it:

msg_show.lua_error Error executing vim.schedule lua callback: ...share/nvim/lazy/template.nvim/lua/template/internals.lua:76: attempt to yield across C-call boundary
stack traceback:
	[C]: in function 'yield'
	...share/nvim/lazy/template.nvim/lua/template/internals.lua:76: in function 'cb'
	...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:206: in function <...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:202>

Do I need to install other supporting plugins for this?

**Comment by doganalper** [comment] 2024-06-13 17:20
@xinmodao Hi, I managed to reproduce your problem. Problem seems to be happening because of dressing plugin. I'm looking into it.

**Comment by doganalper** [comment] 2024-06-14 17:43
@xinmodao This should be fixed with latest PR.

**Closed as completed by doganalper** 2024-06-14 17:43 UTC
